[package]
name = "ray_tracing"
version = "0.1.0"
authors = ["fprince"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
rand = "0.6"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
